export const projects = [
  {
    id: "amotrack",
    title: "AmoTrack",
    cardTranslationKey: "timesheet",
    description:
      "A comprehensive full-stack application for internal business tracking and management, developed during my internship at Amotek. This system handles time tracking, project management, client management, and reporting.",
    icon: null,
    image: "src/assets/timesheet.jpg",
    type: "Internship Project",
    technologies: ["React", "TypeScript", "Fastify", "PostgreSQL", "Drizzle ORM", "Node.js"],
    techs: [],
    isPrivate: true,
  },
  {
    id: "cvo",
    title: "CVO Antwerpen",
    cardTranslationKey: "cvo-automation",
    type: "Team Project",
    description:
      "A backend-focused automation project for CVO Antwerpen School, designed to optimize and automate core administrative processes with deep Google API integration.",
    image: "src/assets/cvo_antwerpen_zuid_cover.jpg",
    technologies: ["C#", ".NET", "Google APIs", "Swagger"],
    githubLink: "",
    isPrivate: true,
  },
  {
    id: "webdev",
    title: "Web Development",
    cardTranslationKey: "webdev",
    description:
      "Simple website with login, MongoDB, and admin features. This project demonstrates my ability to create a complete web application with authentication, database integration, and role-based access control.",
    icon: null,
    image: "src/assets/web_development.jpg",
    type: "Course Project",
    technologies: ["Node.js", "TypeScript", "MongoDB", "Express"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Web_Development",
  },
  {
    id: "game",
    title: "Game Development",
    cardTranslationKey: "game",
    description:
      "2D platformer using MonoGame and C#. This project showcases my ability to work with game development frameworks and implement core gaming mechanics like physics, collision detection, and character movement.",
    icon: null,
    image: "src/assets/game_development.jpg",
    type: "Personal Project",
    technologies: ["C#", "MonoGame"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Game_Development",
  },
  {
    id: "webapi",
    title: "Web API",
    cardTranslationKey: "webapi",
    description:
      "This project demonstrates the development of web services based on open standards such as XML, JSON, and HTTP(S). It includes authentication, rate limiting, and comprehensive documentation.",
    icon: null,
    image: "src/assets/web_api.jpg",
    type: "Course Project",
    technologies: [".NET", "MySQL", "Swagger"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Web_API",
  },
  {
    id: "parkflow",
    title: "ParkFlow",
    cardTranslationKey: "parkflow",
    description:
      "Flutter app that allows users to reserve, view, extend, or cancel parking spots. Users can also select their vehicle from a list and receive notifications about their parking status.",
    icon: null,
    image: "src/assets/park_flow.jpg",
    type: "Team Project",
    technologies: ["Flutter", "Firebase", "Dart"],
    techs: [],
  },
  {
    id: "carinfo",
    title: "Car Info",
    cardTranslationKey: "carinfo",
    description:
      "A project where I tested my skills in React Native focused on mobile devices. I implemented API integrations correctly and used CRUD functions to manage car information data.",
    icon: null,
    image: "src/assets/car_info.jpg",
    type: "Personal Project",
    technologies: ["React Native", "TypeScript", "CSS", "RESTful APIs"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Mobile_Development",
  },
]
