import { SiCss3, SiDart, SiDotnet, SiDrizzle, SiExpress, SiFastify, SiFirebase, SiFlutter, SiMongodb, SiMonogame, SiMysql, SiNodedotjs, SiPostgresql, SiReact, SiReactivex, SiSharp, SiSwagger, SiTypescript } from "react-icons/si";

export const projects = [
  {
    id: "amotrack",
    title: "AmoTrack",
    cardTranslationKey: "timesheet",
    description:
      "A comprehensive full-stack application for internal business tracking and management, developed during my internship at Amotek. This system handles time tracking, project management, client management, and reporting.",
    icon: null,
    image: "assets/timesheet.jpg",
    type: "Internship Project",
    technologies: ["React", "TypeScript", "Fastify", "PostgreSQL", "Drizzle ORM", "Node.js"],
    techs: [],
    isPrivate: true,
  },
  {
    id: "cvo",
    title: "CVO Antwerpen",
    cardTranslationKey: "cvo-automation",
    type: "Team Project",
    description:
      "A backend-focused automation project for CVO Antwerpen School, designed to optimize and automate core administrative processes with deep Google API integration.",
    image: "assets/cvo_antwerpen_zuid_cover.jpg",
    technologies: ["C#", ".NET", "Google APIs", "Swagger"],
    githubLink: "",
    isPrivate: true,
  },
  {
    id: "webdev",
    title: "Web Development",
    cardTranslationKey: "webdev",
    description:
      "Simple website with login, MongoDB, and admin features. This project demonstrates my ability to create a complete web application with authentication, database integration, and role-based access control.",
    icon: null,
    image: "assets/web_development.jpg",
    type: "Course Project",
    technologies: ["Node.js", "TypeScript", "MongoDB", "Express"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Web_Development",
  },
  {
    id: "game",
    title: "Game Development",
    cardTranslationKey: "game",
    description:
      "2D platformer using MonoGame and C#. This project showcases my ability to work with game development frameworks and implement core gaming mechanics like physics, collision detection, and character movement.",
    icon: null,
    image: "assets/game_development.jpg",
    type: "Personal Project",
    technologies: ["C#", "MonoGame"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Game_Development",
  },
  {
    id: "webapi",
    title: "Web API",
    cardTranslationKey: "webapi",
    description:
      "This project demonstrates the development of web services based on open standards such as XML, JSON, and HTTP(S). It includes authentication, rate limiting, and comprehensive documentation.",
    icon: null,
    image: "assets/web_api.jpg",
    type: "Course Project",
    technologies: [".NET", "MySQL", "Swagger"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Web_API",
  },
  {
    id: "parkflow",
    title: "ParkFlow",
    cardTranslationKey: "parkflow",
    description:
      "Flutter app that allows users to reserve, view, extend, or cancel parking spots. Users can also select their vehicle from a list and receive notifications about their parking status.",
    icon: null,
    image: "assets/park_flow.jpg",
    type: "Team Project",
    technologies: ["Flutter", "Firebase", "Dart"],
    techs: [],
  },
  {
    id: "carinfo",
    title: "Car Info",
    cardTranslationKey: "carinfo",
    description:
      "A project where I tested my skills in React Native focused on mobile devices. I implemented API integrations correctly and used CRUD functions to manage car information data.",
    icon: null,
    image: "assets/car_info.jpg",
    type: "Personal Project",
    technologies: ["React Native", "TypeScript", "CSS", "RESTful APIs"],
    techs: [],
    githubLink: "https://github.com/Lenaerts-Nestor/Project_Mobile_Development",
  },
]
export const project_techIcons = {
  React: { icon: SiReact, color: 'text-sky-500' },
  TypeScript: { icon: SiTypescript, color: 'text-blue-600' },
  Fastify: { icon: SiFastify, color: 'text-gray-800 dark:text-gray-200' },
  PostgreSQL: { icon: SiPostgresql, color: 'text-blue-700' },
  'Drizzle ORM': { icon: SiDrizzle, color: 'text-amber-500' },
  'Node.js': { icon: SiNodedotjs, color: 'text-green-600' },
  MongoDB: { icon: SiMongodb, color: 'text-green-500' },
  Express: { icon: SiExpress, color: 'text-gray-700 dark:text-gray-300' },
  C: { icon: SiSharp, color: 'text-purple-600' },
  MonoGame: { icon: SiMonogame, color: 'text-red-600' },
  '.NET': { icon: SiDotnet, color: 'text-purple-700' },
  MySQL: { icon: SiMysql, color: 'text-blue-800' },
  Flutter: { icon: SiFlutter, color: 'text-cyan-500' },
  Firebase: { icon: SiFirebase, color: 'text-amber-500' },
  'React Native': { icon: SiReactivex, color: 'text-sky-600' },
  CSS: { icon: SiCss3, color: 'text-blue-500' },
  Swagger: { icon: SiSwagger, color: 'text-green-600' },
  Dart: { icon: SiDart, color: 'text-blue-400' },
};