export const projects = [
  {
    id: 'timesheet',
    title: 'Timesheet',
    description: 'Web app for internal business tracking and management.',
    icon: null,
    image: 'src/assets/timesheet.jpg',
    type: 'Internship Project',
    technologies: ['React', 'Fastify', 'PostgreSQL', 'Drizzle ORM'],
    techs: [],
  },
  {
    id: 'webdev',
    title: 'Web Development',
    description: 'Simple website with login, MongoDB, and admin features.',
    icon: null,
    image: 'src/assets/web_development.jpg',
    type: 'Course Project',
    technologies: ['Node.js', 'TypeScript', 'MongoDB', 'Express'],
    techs: [],
  },
  {
    id: 'game',
    title: 'Game Development',
    description: '2D platformer using MonoGame and C#.',
    icon: null,
    image: 'src/assets/game_development.jpg',
    type: 'Personal Project',
    technologies: ['C#', 'MonoGame'],
    techs: [],
  },
  {
    id: 'webapi',
    title: 'Web_API',
    description:
      'This project demonstrates the development of web services based on open standards such as XML, JSON, and HTTP(S)..',
    icon: null,
    image: 'src/assets/web_api.jpg',
    type: 'Course Project',
    technologies: ['.NET', 'MySQL'],
    techs: [],
  },
  {
    id: 'parkflow',
    title: 'ParkFlow',
    description:
      'Flutter-app waarmee gebruikers parkeerplekken kunnen reserveren,bekijken, verlengen of annuleren.Gebruikers kunnen ook hun voertuig selecteren uit een lijst van...',
    icon: null,
    image: 'src/assets/park_flow.jpg',
    type: 'Team Project',
    technologies: ['Flutter', 'Firebase'],
    techs: [],
  },
  {
    id: 'carinfo',
    title: 'car_info',
    description:
      "this is a project where i test my skils of react native and focused on mobile devices where i test my skils to get API's correctly and use the CRUDS functions",
    icon: null,
    image: 'src/assets/car_info.jpg',
    type: 'Personal Project',
    technologies: ['React Native', 'TypeScript', 'CSS'],
    techs: [],
  },
];
